#pragma once


// Types used by functions.
#include <wingdi.h>
#include <gl/GL.h>


namespace Wgl
{
	struct _GPU_DEVICE {
		DWORD  cb;
		CHAR   DeviceName[32];
		CHAR   DeviceString[128];
		DWORD  Flags;
		RECT   rcVirtualScreen;
	};

	DECLARE_HANDLE(HPBUFFERARB);
	DECLARE_HANDLE(HPBUFFEREXT);
	DECLARE_HANDLE(HVIDEOOUTPUTDEVICENV);
	DECLARE_HANDLE(HPVIDEODEV);
	DECLARE_HANDLE(HPGPUNV);
	DECLARE_HANDLE(HGPUNV);
	DECLARE_HANDLE(HVIDEOINPUTDEVICENV);

	typedef struct _GPU_DEVICE GPU_DEVICE;
	typedef struct _GPU_DEVICE *PGPU_DEVICE;


	typedef void* (WINAPI *PFNWGLALLOCATEMEMORYNVPROC)(GLsizei size, GLfloat readfreq, GLfloat writefreq, GLfloat priority);
	typedef BOOL (WINAPI *PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC)(HDC hDC, const HANDLE * pEvent, const LPVOID * pAddress, const DWORD * pSize, UINT count);
	typedef BOOL (WINAPI *PFNWGLBEGINFRAMETRACKINGI3DPROC)(void);
	typedef GLboolean (WINAPI *PFNWGLBINDDISPLAYCOLORTABLEEXTPROC)(GLushort id);
	typedef BOOL (WINAPI *PFNWGLBINDSWAPBARRIERNVPROC)(GLuint group, GLuint barrier);
	typedef BOOL (WINAPI *PFNWGLBINDTEXIMAGEARBPROC)(HPBUFFERARB hPbuffer, int iBuffer);
	typedef BOOL (WINAPI *PFNWGLBINDVIDEOCAPTUREDEVICENVPROC)(UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice);
	typedef BOOL (WINAPI *PFNWGLBINDVIDEODEVICENVPROC)(HDC hDc, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int * piAttribList);
	typedef BOOL (WINAPI *PFNWGLBINDVIDEOIMAGENVPROC)(HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer);
	typedef VOID (WINAPI *PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC)(HGLRC dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
	typedef BOOL (WINAPI *PFNWGLCHOOSEPIXELFORMATARBPROC)(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
	typedef BOOL (WINAPI *PFNWGLCHOOSEPIXELFORMATEXTPROC)(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
	typedef BOOL (WINAPI *PFNWGLCOPYIMAGESUBDATANVPROC)(HGLRC hSrcRC, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, HGLRC hDstRC, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
	typedef HDC (WINAPI *PFNWGLCREATEAFFINITYDCNVPROC)(const HGPUNV * phGpuList);
	typedef HGLRC (WINAPI *PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC)(UINT id);
	typedef HGLRC (WINAPI *PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC)(UINT id, HGLRC hShareContext, const int * attribList);
	typedef HANDLE (WINAPI *PFNWGLCREATEBUFFERREGIONARBPROC)(HDC hDC, int iLayerPlane, UINT uType);
	typedef HGLRC (WINAPI *PFNWGLCREATECONTEXTATTRIBSARBPROC)(HDC hDC, HGLRC hShareContext, const int * attribList);
	typedef GLboolean (WINAPI *PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC)(GLushort id);
	typedef LPVOID (WINAPI *PFNWGLCREATEIMAGEBUFFERI3DPROC)(HDC hDC, DWORD dwSize, UINT uFlags);
	typedef HPBUFFERARB (WINAPI *PFNWGLCREATEPBUFFERARBPROC)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
	typedef HPBUFFEREXT (WINAPI *PFNWGLCREATEPBUFFEREXTPROC)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
	typedef BOOL (WINAPI *PFNWGLDXCLOSEDEVICENVPROC)(HANDLE hDevice);
	typedef BOOL (WINAPI *PFNWGLDXLOCKOBJECTSNVPROC)(HANDLE hDevice, GLint count, HANDLE * hObjects);
	typedef BOOL (WINAPI *PFNWGLDXOBJECTACCESSNVPROC)(HANDLE hObject, GLenum access);
	typedef HANDLE (WINAPI *PFNWGLDXOPENDEVICENVPROC)(void * dxDevice);
	typedef HANDLE (WINAPI *PFNWGLDXREGISTEROBJECTNVPROC)(HANDLE hDevice, void * dxObject, GLuint name, GLenum type, GLenum access);
	typedef BOOL (WINAPI *PFNWGLDXSETRESOURCESHAREHANDLENVPROC)(void * dxObject, HANDLE shareHandle);
	typedef BOOL (WINAPI *PFNWGLDXUNLOCKOBJECTSNVPROC)(HANDLE hDevice, GLint count, HANDLE * hObjects);
	typedef BOOL (WINAPI *PFNWGLDXUNREGISTEROBJECTNVPROC)(HANDLE hDevice, HANDLE hObject);
	typedef BOOL (WINAPI *PFNWGLDELAYBEFORESWAPNVPROC)(HDC hDC, GLfloat seconds);
	typedef BOOL (WINAPI *PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC)(HGLRC hglrc);
	typedef VOID (WINAPI *PFNWGLDELETEBUFFERREGIONARBPROC)(HANDLE hRegion);
	typedef BOOL (WINAPI *PFNWGLDELETEDCNVPROC)(HDC hdc);
	typedef VOID (WINAPI *PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC)(GLushort id);
	typedef BOOL (WINAPI *PFNWGLDESTROYIMAGEBUFFERI3DPROC)(HDC hDC, LPVOID pAddress);
	typedef BOOL (WINAPI *PFNWGLDESTROYPBUFFERARBPROC)(HPBUFFERARB hPbuffer);
	typedef BOOL (WINAPI *PFNWGLDESTROYPBUFFEREXTPROC)(HPBUFFEREXT hPbuffer);
	typedef BOOL (WINAPI *PFNWGLDISABLEFRAMELOCKI3DPROC)(void);
	typedef BOOL (WINAPI *PFNWGLDISABLEGENLOCKI3DPROC)(HDC hDC);
	typedef BOOL (WINAPI *PFNWGLENABLEFRAMELOCKI3DPROC)(void);
	typedef BOOL (WINAPI *PFNWGLENABLEGENLOCKI3DPROC)(HDC hDC);
	typedef BOOL (WINAPI *PFNWGLENDFRAMETRACKINGI3DPROC)(void);
	typedef BOOL (WINAPI *PFNWGLENUMGPUDEVICESNVPROC)(HGPUNV hGpu, UINT iDeviceIndex, PGPU_DEVICE lpGpuDevice);
	typedef BOOL (WINAPI *PFNWGLENUMGPUSFROMAFFINITYDCNVPROC)(HDC hAffinityDC, UINT iGpuIndex, HGPUNV * hGpu);
	typedef BOOL (WINAPI *PFNWGLENUMGPUSNVPROC)(UINT iGpuIndex, HGPUNV * phGpu);
	typedef UINT (WINAPI *PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC)(HDC hDc, HVIDEOINPUTDEVICENV * phDeviceList);
	typedef int (WINAPI *PFNWGLENUMERATEVIDEODEVICESNVPROC)(HDC hDc, HVIDEOOUTPUTDEVICENV * phDeviceList);
	typedef void (WINAPI *PFNWGLFREEMEMORYNVPROC)(void * pointer);
	typedef BOOL (WINAPI *PFNWGLGENLOCKSAMPLERATEI3DPROC)(HDC hDC, UINT uRate);
	typedef BOOL (WINAPI *PFNWGLGENLOCKSOURCEDELAYI3DPROC)(HDC hDC, UINT uDelay);
	typedef BOOL (WINAPI *PFNWGLGENLOCKSOURCEEDGEI3DPROC)(HDC hDC, UINT uEdge);
	typedef BOOL (WINAPI *PFNWGLGENLOCKSOURCEI3DPROC)(HDC hDC, UINT uSource);
	typedef UINT (WINAPI *PFNWGLGETCONTEXTGPUIDAMDPROC)(HGLRC hglrc);
	typedef HGLRC (WINAPI *PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC)(void);
	typedef HDC (WINAPI *PFNWGLGETCURRENTREADDCARBPROC)(void);
	typedef HDC (WINAPI *PFNWGLGETCURRENTREADDCEXTPROC)(void);
	typedef BOOL (WINAPI *PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC)(HDC hDC, int iAttribute, int * piValue);
	typedef BOOL (WINAPI *PFNWGLGETFRAMEUSAGEI3DPROC)(float * pUsage);
	typedef UINT (WINAPI *PFNWGLGETGPUIDSAMDPROC)(UINT maxCount, UINT * ids);
	typedef INT (WINAPI *PFNWGLGETGPUINFOAMDPROC)(UINT id, INT property, GLenum dataType, UINT size, void * data);
	typedef BOOL (WINAPI *PFNWGLGETGAMMATABLEI3DPROC)(HDC hDC, int iEntries, USHORT * puRed, USHORT * puGreen, USHORT * puBlue);
	typedef BOOL (WINAPI *PFNWGLGETGAMMATABLEPARAMETERSI3DPROC)(HDC hDC, int iAttribute, int * piValue);
	typedef BOOL (WINAPI *PFNWGLGETGENLOCKSAMPLERATEI3DPROC)(HDC hDC, UINT * uRate);
	typedef BOOL (WINAPI *PFNWGLGETGENLOCKSOURCEDELAYI3DPROC)(HDC hDC, UINT * uDelay);
	typedef BOOL (WINAPI *PFNWGLGETGENLOCKSOURCEEDGEI3DPROC)(HDC hDC, UINT * uEdge);
	typedef BOOL (WINAPI *PFNWGLGETGENLOCKSOURCEI3DPROC)(HDC hDC, UINT * uSource);
	typedef BOOL (WINAPI *PFNWGLGETMSCRATEOMLPROC)(HDC hdc, INT32 * numerator, INT32 * denominator);
	typedef HDC (WINAPI *PFNWGLGETPBUFFERDCARBPROC)(HPBUFFERARB hPbuffer);
	typedef HDC (WINAPI *PFNWGLGETPBUFFERDCEXTPROC)(HPBUFFEREXT hPbuffer);
	typedef BOOL (WINAPI *PFNWGLGETPIXELFORMATATTRIBFVARBPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, FLOAT * pfValues);
	typedef BOOL (WINAPI *PFNWGLGETPIXELFORMATATTRIBFVEXTPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, FLOAT * pfValues);
	typedef BOOL (WINAPI *PFNWGLGETPIXELFORMATATTRIBIVARBPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, int * piValues);
	typedef BOOL (WINAPI *PFNWGLGETPIXELFORMATATTRIBIVEXTPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, int * piValues);
	typedef int (WINAPI *PFNWGLGETSWAPINTERVALEXTPROC)(void);
	typedef BOOL (WINAPI *PFNWGLGETSYNCVALUESOMLPROC)(HDC hdc, INT64 * ust, INT64 * msc, INT64 * sbc);
	typedef BOOL (WINAPI *PFNWGLGETVIDEODEVICENVPROC)(HDC hDC, int numDevices, HPVIDEODEV * hVideoDevice);
	typedef BOOL (WINAPI *PFNWGLGETVIDEOINFONVPROC)(HPVIDEODEV hpVideoDevice, unsigned long * pulCounterOutputPbuffer, unsigned long * pulCounterOutputVideo);
	typedef BOOL (WINAPI *PFNWGLISENABLEDFRAMELOCKI3DPROC)(BOOL * pFlag);
	typedef BOOL (WINAPI *PFNWGLISENABLEDGENLOCKI3DPROC)(HDC hDC, BOOL * pFlag);
	typedef BOOL (WINAPI *PFNWGLJOINSWAPGROUPNVPROC)(HDC hDC, GLuint group);
	typedef GLboolean (WINAPI *PFNWGLLOADDISPLAYCOLORTABLEEXTPROC)(const GLushort * table, GLuint length);
	typedef BOOL (WINAPI *PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
	typedef BOOL (WINAPI *PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC)(HGLRC hglrc);
	typedef BOOL (WINAPI *PFNWGLMAKECONTEXTCURRENTARBPROC)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
	typedef BOOL (WINAPI *PFNWGLMAKECONTEXTCURRENTEXTPROC)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
	typedef BOOL (WINAPI *PFNWGLQUERYCURRENTCONTEXTNVPROC)(int iAttribute, int * piValue);
	typedef BOOL (WINAPI *PFNWGLQUERYFRAMECOUNTNVPROC)(HDC hDC, GLuint * count);
	typedef BOOL (WINAPI *PFNWGLQUERYFRAMELOCKMASTERI3DPROC)(BOOL * pFlag);
	typedef BOOL (WINAPI *PFNWGLQUERYFRAMETRACKINGI3DPROC)(DWORD * pFrameCount, DWORD * pMissedFrames, float * pLastMissedUsage);
	typedef BOOL (WINAPI *PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC)(HDC hDC, UINT * uMaxLineDelay, UINT * uMaxPixelDelay);
	typedef BOOL (WINAPI *PFNWGLQUERYMAXSWAPGROUPSNVPROC)(HDC hDC, GLuint * maxGroups, GLuint * maxBarriers);
	typedef BOOL (WINAPI *PFNWGLQUERYPBUFFERARBPROC)(HPBUFFERARB hPbuffer, int iAttribute, int * piValue);
	typedef BOOL (WINAPI *PFNWGLQUERYPBUFFEREXTPROC)(HPBUFFEREXT hPbuffer, int iAttribute, int * piValue);
	typedef BOOL (WINAPI *PFNWGLQUERYSWAPGROUPNVPROC)(HDC hDC, GLuint * group, GLuint * barrier);
	typedef BOOL (WINAPI *PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int * piValue);
	typedef BOOL (WINAPI *PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC)(HDC hDC, const LPVOID * pAddress, UINT count);
	typedef int (WINAPI *PFNWGLRELEASEPBUFFERDCARBPROC)(HPBUFFERARB hPbuffer, HDC hDC);
	typedef int (WINAPI *PFNWGLRELEASEPBUFFERDCEXTPROC)(HPBUFFEREXT hPbuffer, HDC hDC);
	typedef BOOL (WINAPI *PFNWGLRELEASETEXIMAGEARBPROC)(HPBUFFERARB hPbuffer, int iBuffer);
	typedef BOOL (WINAPI *PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
	typedef BOOL (WINAPI *PFNWGLRELEASEVIDEODEVICENVPROC)(HPVIDEODEV hVideoDevice);
	typedef BOOL (WINAPI *PFNWGLRELEASEVIDEOIMAGENVPROC)(HPBUFFERARB hPbuffer, int iVideoBuffer);
	typedef BOOL (WINAPI *PFNWGLRESETFRAMECOUNTNVPROC)(HDC hDC);
	typedef BOOL (WINAPI *PFNWGLRESTOREBUFFERREGIONARBPROC)(HANDLE hRegion, int x, int y, int width, int height, int xSrc, int ySrc);
	typedef BOOL (WINAPI *PFNWGLSAVEBUFFERREGIONARBPROC)(HANDLE hRegion, int x, int y, int width, int height);
	typedef BOOL (WINAPI *PFNWGLSENDPBUFFERTOVIDEONVPROC)(HPBUFFERARB hPbuffer, int iBufferType, unsigned long * pulCounterPbuffer, BOOL bBlock);
	typedef BOOL (WINAPI *PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC)(HDC hDC, int iAttribute, const int * piValue);
	typedef BOOL (WINAPI *PFNWGLSETGAMMATABLEI3DPROC)(HDC hDC, int iEntries, const USHORT * puRed, const USHORT * puGreen, const USHORT * puBlue);
	typedef BOOL (WINAPI *PFNWGLSETGAMMATABLEPARAMETERSI3DPROC)(HDC hDC, int iAttribute, const int * piValue);
	typedef BOOL (WINAPI *PFNWGLSETPBUFFERATTRIBARBPROC)(HPBUFFERARB hPbuffer, const int * piAttribList);
	typedef BOOL (WINAPI *PFNWGLSETSTEREOEMITTERSTATE3DLPROC)(HDC hDC, UINT uState);
	typedef INT64 (WINAPI *PFNWGLSWAPBUFFERSMSCOMLPROC)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder);
	typedef BOOL (WINAPI *PFNWGLSWAPINTERVALEXTPROC)(int interval);
	typedef INT64 (WINAPI *PFNWGLSWAPLAYERBUFFERSMSCOMLPROC)(HDC hdc, INT fuPlanes, INT64 target_msc, INT64 divisor, INT64 remainder);
	typedef BOOL (WINAPI *PFNWGLWAITFORMSCOMLPROC)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder, INT64 * ust, INT64 * msc, INT64 * sbc);
	typedef BOOL (WINAPI *PFNWGLWAITFORSBCOMLPROC)(HDC hdc, INT64 target_sbc, INT64 * ust, INT64 * msc, INT64 * sbc);


	extern PFNWGLALLOCATEMEMORYNVPROC						allocate_memory_nv;
	extern PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC			associate_image_buffer_events_i3d;
	extern PFNWGLBEGINFRAMETRACKINGI3DPROC					begin_frame_tracking_i3d;
	extern PFNWGLBINDDISPLAYCOLORTABLEEXTPROC				bind_display_color_table_ext;
	extern PFNWGLBINDSWAPBARRIERNVPROC						bind_swap_barrier_nv;
	extern PFNWGLBINDTEXIMAGEARBPROC						bind_tex_image_arb;
	extern PFNWGLBINDVIDEOCAPTUREDEVICENVPROC				bind_video_capture_device_nv;
	extern PFNWGLBINDVIDEODEVICENVPROC						bind_video_device_nv;
	extern PFNWGLBINDVIDEOIMAGENVPROC						bind_video_image_nv;
	extern PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC				blit_context_framebuffer_amd;
	extern PFNWGLCHOOSEPIXELFORMATARBPROC					choose_pixel_format_arb;
	extern PFNWGLCHOOSEPIXELFORMATEXTPROC					choose_pixel_format_ext;
	extern PFNWGLCOPYIMAGESUBDATANVPROC						copy_image_sub_data_nv;
	extern PFNWGLCREATEAFFINITYDCNVPROC						create_affinity_dc_nv;
	extern PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC				create_associated_context_amd;
	extern PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC		create_associated_context_attribs_amd;
	extern PFNWGLCREATEBUFFERREGIONARBPROC					create_buffer_region_arb;
	extern PFNWGLCREATECONTEXTATTRIBSARBPROC				create_context_attribs_arb;
	extern PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC				create_display_color_table_ext;
	extern PFNWGLCREATEIMAGEBUFFERI3DPROC					create_image_buffer_i3d;
	extern PFNWGLCREATEPBUFFERARBPROC						create_pbuffer_arb;
	extern PFNWGLCREATEPBUFFEREXTPROC						create_pbuffer_ext;
	extern PFNWGLDXCLOSEDEVICENVPROC						dx_close_device_nv;
	extern PFNWGLDXLOCKOBJECTSNVPROC						dx_lock_objects_nv;
	extern PFNWGLDXOBJECTACCESSNVPROC						dx_object_access_nv;
	extern PFNWGLDXOPENDEVICENVPROC							dx_open_device_nv;
	extern PFNWGLDXREGISTEROBJECTNVPROC						dx_register_object_nv;
	extern PFNWGLDXSETRESOURCESHAREHANDLENVPROC				dx_set_resource_share_handle_nv;
	extern PFNWGLDXUNLOCKOBJECTSNVPROC						dx_unlock_objects_nv;
	extern PFNWGLDXUNREGISTEROBJECTNVPROC					dx_unregister_object_nv;
	extern PFNWGLDELAYBEFORESWAPNVPROC						delay_before_swap_nv;
	extern PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC				delete_associated_context_amd;
	extern PFNWGLDELETEBUFFERREGIONARBPROC					delete_buffer_region_arb;
	extern PFNWGLDELETEDCNVPROC								delete_dc_nv;
	extern PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC			destroy_display_color_table_ext;
	extern PFNWGLDESTROYIMAGEBUFFERI3DPROC					destroy_image_buffer_i3d;
	extern PFNWGLDESTROYPBUFFERARBPROC						destroy_pbuffer_arb;
	extern PFNWGLDESTROYPBUFFEREXTPROC						destroy_pbuffer_ext;
	extern PFNWGLDISABLEFRAMELOCKI3DPROC					disable_frame_lock_i3d;
	extern PFNWGLDISABLEGENLOCKI3DPROC						disable_genlock_i3d;
	extern PFNWGLENABLEFRAMELOCKI3DPROC						enable_frame_lock_i3d;
	extern PFNWGLENABLEGENLOCKI3DPROC						enable_genlock_i3d;
	extern PFNWGLENDFRAMETRACKINGI3DPROC					end_frame_tracking_i3d;
	extern PFNWGLENUMGPUDEVICESNVPROC						enum_gpu_devices_nv;
	extern PFNWGLENUMGPUSFROMAFFINITYDCNVPROC				enum_gpus_from_affinity_dc_nv;
	extern PFNWGLENUMGPUSNVPROC								enum_gpus_nv;
	extern PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC			enumerate_video_capture_devices_nv;
	extern PFNWGLENUMERATEVIDEODEVICESNVPROC				enumerate_video_devices_nv;
	extern PFNWGLFREEMEMORYNVPROC							free_memory_nv;
	extern PFNWGLGENLOCKSAMPLERATEI3DPROC					genlock_sample_rate_i3d;
	extern PFNWGLGENLOCKSOURCEDELAYI3DPROC					genlock_source_delay_i3d;
	extern PFNWGLGENLOCKSOURCEEDGEI3DPROC					genlock_source_edge_i3d;
	extern PFNWGLGENLOCKSOURCEI3DPROC						genlock_source_i3d;
	extern PFNWGLGETCONTEXTGPUIDAMDPROC						get_context_gpu_id_amd;
	extern PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC			get_current_associated_context_amd;
	extern PFNWGLGETCURRENTREADDCARBPROC					get_current_read_dc_arb;
	extern PFNWGLGETCURRENTREADDCEXTPROC					get_current_read_dc_ext;
	extern PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC			get_digital_video_parameters_i3d;
	extern PFNWGLGETFRAMEUSAGEI3DPROC						get_frame_usage_i3d;
	extern PFNWGLGETGPUIDSAMDPROC							get_gpu_ids_amd;
	extern PFNWGLGETGPUINFOAMDPROC							get_gpu_info_amd;
	extern PFNWGLGETGAMMATABLEI3DPROC						get_gamma_table_i3d;
	extern PFNWGLGETGAMMATABLEPARAMETERSI3DPROC				get_gamma_table_parameters_i3d;
	extern PFNWGLGETGENLOCKSAMPLERATEI3DPROC				get_genlock_sample_rate_i3d;
	extern PFNWGLGETGENLOCKSOURCEDELAYI3DPROC				get_genlock_source_delay_i3d;
	extern PFNWGLGETGENLOCKSOURCEEDGEI3DPROC				get_genlock_source_edge_i3d;
	extern PFNWGLGETGENLOCKSOURCEI3DPROC					get_genlock_source_i3d;
	extern PFNWGLGETMSCRATEOMLPROC							get_msc_rate_oml;
	extern PFNWGLGETPBUFFERDCARBPROC						get_pbuffer_dc_arb;
	extern PFNWGLGETPBUFFERDCEXTPROC						get_pbuffer_dc_ext;
	extern PFNWGLGETPIXELFORMATATTRIBFVARBPROC				get_pixel_format_attribfv_arb;
	extern PFNWGLGETPIXELFORMATATTRIBFVEXTPROC				get_pixel_format_attribfv_ext;
	extern PFNWGLGETPIXELFORMATATTRIBIVARBPROC				get_pixel_format_attribiv_arb;
	extern PFNWGLGETPIXELFORMATATTRIBIVEXTPROC				get_pixel_format_attribiv_ext;
	extern PFNWGLGETSWAPINTERVALEXTPROC						get_swap_interval_ext;
	extern PFNWGLGETSYNCVALUESOMLPROC						get_sync_values_oml;
	extern PFNWGLGETVIDEODEVICENVPROC						get_video_device_nv;
	extern PFNWGLGETVIDEOINFONVPROC							get_video_info_nv;
	extern PFNWGLISENABLEDFRAMELOCKI3DPROC					is_enabled_frame_lock_i3d;
	extern PFNWGLISENABLEDGENLOCKI3DPROC					is_enabled_genlock_i3d;
	extern PFNWGLJOINSWAPGROUPNVPROC						join_swap_group_nv;
	extern PFNWGLLOADDISPLAYCOLORTABLEEXTPROC				load_display_color_table_ext;
	extern PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC				lock_video_capture_device_nv;
	extern PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC		make_associated_context_current_amd;
	extern PFNWGLMAKECONTEXTCURRENTARBPROC					make_context_current_arb;
	extern PFNWGLMAKECONTEXTCURRENTEXTPROC					make_context_current_ext;
	extern PFNWGLQUERYCURRENTCONTEXTNVPROC					query_current_context_nv;
	extern PFNWGLQUERYFRAMECOUNTNVPROC						query_frame_count_nv;
	extern PFNWGLQUERYFRAMELOCKMASTERI3DPROC				query_frame_lock_master_i3d;
	extern PFNWGLQUERYFRAMETRACKINGI3DPROC					query_frame_tracking_i3d;
	extern PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC			query_genlock_max_source_delay_i3d;
	extern PFNWGLQUERYMAXSWAPGROUPSNVPROC					query_max_swap_groups_nv;
	extern PFNWGLQUERYPBUFFERARBPROC						query_pbuffer_arb;
	extern PFNWGLQUERYPBUFFEREXTPROC						query_pbuffer_ext;
	extern PFNWGLQUERYSWAPGROUPNVPROC						query_swap_group_nv;
	extern PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC				query_video_capture_device_nv;
	extern PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC			release_image_buffer_events_i3d;
	extern PFNWGLRELEASEPBUFFERDCARBPROC					release_pbuffer_dc_arb;
	extern PFNWGLRELEASEPBUFFERDCEXTPROC					release_pbuffer_dc_ext;
	extern PFNWGLRELEASETEXIMAGEARBPROC						release_tex_image_arb;
	extern PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC			release_video_capture_device_nv;
	extern PFNWGLRELEASEVIDEODEVICENVPROC					release_video_device_nv;
	extern PFNWGLRELEASEVIDEOIMAGENVPROC					release_video_image_nv;
	extern PFNWGLRESETFRAMECOUNTNVPROC						reset_frame_count_nv;
	extern PFNWGLRESTOREBUFFERREGIONARBPROC					restore_buffer_region_arb;
	extern PFNWGLSAVEBUFFERREGIONARBPROC					save_buffer_region_arb;
	extern PFNWGLSENDPBUFFERTOVIDEONVPROC					send_pbuffer_to_video_nv;
	extern PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC			set_digital_video_parameters_i3d;
	extern PFNWGLSETGAMMATABLEI3DPROC						set_gamma_table_i3d;
	extern PFNWGLSETGAMMATABLEPARAMETERSI3DPROC				set_gamma_table_parameters_i3d;
	extern PFNWGLSETPBUFFERATTRIBARBPROC					set_pbuffer_attrib_arb;
	extern PFNWGLSETSTEREOEMITTERSTATE3DLPROC				set_stereo_emitter_state3d_l;
	extern PFNWGLSWAPBUFFERSMSCOMLPROC						swap_buffers_msc_oml;
	extern PFNWGLSWAPINTERVALEXTPROC						swap_interval_ext;
	extern PFNWGLSWAPLAYERBUFFERSMSCOMLPROC					swap_layer_buffers_msc_oml;
	extern PFNWGLWAITFORMSCOMLPROC							wait_for_msc_oml;
	extern PFNWGLWAITFORSBCOMLPROC							wait_for_sbc_oml;
}
